# Generated by Django 5.1.4 on 2025-01-15 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('payment_type', models.CharField(choices=[('CARD', 'CARD'), ('PAYLOV', 'PAYLOV')], max_length=50, verbose_name='Payment type')),
                ('method_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Method type')),
                ('request_headers', models.TextField(null=True, verbose_name='Request Headers')),
                ('request_body', models.TextField(null=True, verbose_name='Request Body')),
                ('response_headers', models.TextField(null=True, verbose_name='Response Headers')),
                ('response_body', models.TextField(null=True, verbose_name='Response Body')),
                ('response_status_code', models.PositiveSmallIntegerField(null=True, verbose_name='Response status code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=32, verbose_name='Status')),
                ('remote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remote id')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='TAX Amount')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Canceled at')),
                ('payment_type', models.CharField(choices=[('CARD', 'CARD'), ('PAYLOV', 'PAYLOV')], verbose_name='Payment Type')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra')),
                ('is_notification_sent', models.BooleanField(default=False, verbose_name='Is notification sent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'Transaction',
                'ordering': ('remote_id',),
            },
        ),
    ]
